version: 2
jobs:
  build:
    working_directory: /javaperks-product-api
    docker:
      - image: docker:19.03.2-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/javaperks-product-api.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/javaperks-product-api.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=javaperks-product-api -t jubican/javaperks-product-api:1.1.2 .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/javaperks-product-api.tar jubican/javaperks-product-api
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/javaperks-product-api.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push jubican/javaperks-product-api:1.1.2
            fi
